const EVENTS = [
    {
        id: 1,
        name: 'Event 1',
        date: '2021-01-01',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 2,
        name: 'Event 2',
        date: '2021-01-02',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 3,
        name: 'Event 3',
        date: '2021-01-03',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 4,
        name: 'Event 4',
        date: '2021-01-04',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 5,
        name: 'Event 5',
        date: '2021-01-05',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 6,
        name: 'Event 6',
        date: '2021-01-06',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 7,
        name: 'Event 7',
        date: '2021-01-07',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 8,
        name: 'Event 8',
        date: '2021-01-08',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 9,
        name: 'Event 9',
        date: '2021-01-09',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 10,
        name: 'Event 10',
        date: '2021-01-10',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 11,
        name: 'Event 11',
        date: '2021-01-11',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 12,
        name: 'Event 12',
        date: '2021-01-12',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 13,
        name: 'Event 13',
        date: '2021-01-13',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 14,
        name: 'Event 14',
        date: '2021-01-14',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 15,
        name: 'Event 15',
        date: '2021-01-15',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    },
    {
        id: 16,
        name: 'Event 16',
        date: '2021-01-16',
        time: '12:00',
        duration: 1,
        prizes_1: 'Prize 1',
        prizes_2: 'Prize 2',
        description: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    }
]

// video 17.24